name: cIP
main: me.PS.cIP.cIP
version: 0.2
author: P_S
load: POSTWORLD
website: http://www.ps-bred02.eu/
description: >
             Censorship IP plugin
commands:
  cIP:
    description: Plugin commands ...
  cIP reload:
    description: Reload plugin